# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles/reglive.ui'
#
# Created: Mon Sep  5 23:50:00 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1216, 828)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 20, 1181, 741))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.layoutWidget = QtGui.QWidget(self.page)
        self.layoutWidget.setGeometry(QtCore.QRect(310, 140, 601, 441))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.compDescLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.compDescLineEdit.setObjectName("compDescLineEdit")
        self.gridLayout.addWidget(self.compDescLineEdit, 2, 0, 1, 4)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 4)
        self.outputDirectoryLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.outputDirectoryLineEdit.setObjectName("outputDirectoryLineEdit")
        self.gridLayout.addWidget(self.outputDirectoryLineEdit, 5, 0, 1, 3)
        self.browsePushButton = QtGui.QPushButton(self.layoutWidget)
        self.browsePushButton.setObjectName("browsePushButton")
        self.gridLayout.addWidget(self.browsePushButton, 5, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 8, 0, 1, 1)
        self.currentFilesCheckBox = QtGui.QCheckBox(self.layoutWidget)
        self.currentFilesCheckBox.setObjectName("currentFilesCheckBox")
        self.gridLayout.addWidget(self.currentFilesCheckBox, 8, 1, 1, 1)
        self.backupFilesCheckBox = QtGui.QCheckBox(self.layoutWidget)
        self.backupFilesCheckBox.setObjectName("backupFilesCheckBox")
        self.gridLayout.addWidget(self.backupFilesCheckBox, 8, 2, 1, 2)
        self.acquireFilesPushButton = QtGui.QPushButton(self.layoutWidget)
        self.acquireFilesPushButton.setObjectName("acquireFilesPushButton")
        self.gridLayout.addWidget(self.acquireFilesPushButton, 10, 1, 1, 2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 4)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 9, 0, 1, 4)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 4)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 4, 0, 1, 4)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 7, 0, 1, 4)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.layoutWidget1 = QtGui.QWidget(self.page_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 1171, 711))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.resultsLabel = QtGui.QLabel(self.layoutWidget1)
        self.resultsLabel.setText("")
        self.resultsLabel.setObjectName("resultsLabel")
        self.gridLayout_2.addWidget(self.resultsLabel, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1216, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Registry Decoder - Digital Forensics Solutions", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Computer Description", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Output Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.browsePushButton.setText(QtGui.QApplication.translate("MainWindow", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Acquire:", None, QtGui.QApplication.UnicodeUTF8))
        self.currentFilesCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Current Files", None, QtGui.QApplication.UnicodeUTF8))
        self.backupFilesCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Backup Files", None, QtGui.QApplication.UnicodeUTF8))
        self.acquireFilesPushButton.setText(QtGui.QApplication.translate("MainWindow", "Acquire Files", None, QtGui.QApplication.UnicodeUTF8))

